# Define UI for application that draws a histogram
shinyUI(fluidPage(theme = shinythemes::shinytheme("superhero"),

    # Application title
    titlePanel("Siaya County HTS Risk"),

    # Sidebar with a slider input for number of bins
    sidebarLayout(
        sidebarPanel(
            numericInput("ageattest",
                         "Client Age",
                         value = 0,
                         min = 0,
                         max = 100),
            selectInput("maritalstatus",
                        "Marital Status",
                        choices = c("", as.character(unique(dat$MaritalStatus))),
                        selected = NULL),
            selectInput("gender",
                        "Gender",
                        choices = c("", as.character(unique(dat$Gender))),
                        selected = NULL),
            selectInput("sitecode",
                        "SiteCode",
                        choices = c("", facilities$Name),
                        selected = NULL),
            selectInput("KPtype",
                        "Key Population type:",
                        choices = c("", as.character(unique(dat$KeyPopulationType))),
                        selected = NULL),
            selectInput("patientdisabled",
                        "Patient Disabled",
                        choices = c("", as.character(unique(dat$PatientDisabled))),
                        selected = NULL),
            selectInput("clienttestedas",
                        "Client Tested As",
                        choices = c("", as.character(unique(dat$ClientTestedAs))),
                        selected = NULL),
            selectInput("entrypoint",
                        "Entry Point",
                        choices = c("", as.character(unique(dat$EntryPoint))),
                        selected = NULL),
            selectInput("testingstrategy",
                        "Testing Strategy",
                        choices = c("", as.character(unique(dat$TestingStrategy))),
                        selected = NULL),
            selectInput("tbscreening",
                        "TB Screening",
                        choices = c("", as.character(unique(dat$TBScreening))),
                        selected = NULL),
            selectInput("clientselftested",
                        "Client Self Tested",
                        choices = c("", as.character(unique(dat$ClientSelfTested))),
                        selected = NULL),
            selectInput("evertested",
                        "Ever Tested for HIV",
                        choices = c("", as.character(unique(dat$EverTestedForHIV))),
                        selected = NULL),
            conditionalPanel(
                condition = "input.evertested == 'Yes'",
                numericInput("monthssincelasttest",
                             "Months Since Last Test",
                             value = 0,
                             min = 0,
                             max = 50))
        ),

        # Show a plot of the generated distribution
        mainPanel(width = 6,
            actionButton('pred', 'Generate Prediction'),
            br(),
            br(),
            verbatimTextOutput("predText"),
            br(),
            br(),
            actionButton('recPred', 'Save Prediction'),
            br(),
            br(),
            br(),
            br(),
            actionButton('recResult', 'Record Test Result')
        )
    )
))
