# Define UI for application that draws a histogram
shinyUI(fluidPage(theme = shinythemes::shinytheme("superhero"),

    # Application title
    titlePanel("Siaya County HTS Risk"),

    # Sidebar with a slider input for number of bins
    sidebarLayout(
        sidebarPanel(
            selectInput("KPtype",
                        "Key Population type:",
                        choices = c("", KPTYPE),
                        selected = NULL),
            selectInput("maritalstatus",
                        "Marital Status",
                        choices = c("", MS),
                        selected = NULL),
            selectInput("gender",
                        "Gender",
                        choices = c("", GENDER),
                        selected = NULL),
            selectInput("patientdisabled",
                        "Patient Disabled",
                        choices = c("", PD),
                        selected = NULL),
            selectInput("clienttestedas",
                        "Client Tested As",
                        choices = c("", CTA),
                        selected = NULL),
            selectInput("entrypoint",
                        "Entry Point",
                        choices = c("", EP),
                        selected = NULL),
            selectInput("testingstrategy",
                        "Testing Strategy",
                        choices = c("", TS),
                        selected = NULL),
            selectInput("tbscreening",
                        "TB Screening",
                        choices = c("", TB),
                        selected = NULL),
            selectInput("clientselftested",
                        "Client Self Tested",
                        choices = c("", CST),
                        selected = NULL),
            selectInput("sitecode",
                        "SiteCode",
                        choices = c("", SITECODE),
                        selected = NULL),
            numericInput("ageattest",
                         "Client Age",
                         value = 0,
                         min = 0,
                         max = 100),
            selectInput("evertested",
                        "Ever Tested for HIV",
                        choices = c("", ETHIV),
                        selected = NULL),
            conditionalPanel(
                condition = "input.evertested == 'Yes'",
                numericInput("monthssincelasttest",
                             "Months Since Last Test",
                             value = 0,
                             min = 0,
                             max = 50))
        ),

        # Show a plot of the generated distribution
        mainPanel(width = 6,
            actionButton('pred', 'Generate Prediction'),
            br(),
            br(),
            verbatimTextOutput("predText"),
            br(),
            br(),
            actionButton('recPred', 'Save Prediction'),
            br(),
            br(),
            br(),
            br(),
            actionButton('recResult', 'Record Test Result')
        )
    )
))
